export enum Sport {
    Football = 1,
    Basketball = 2,
    Rugby = 3,
    Tennis = 4,
    Boxe = 5,
    FootballAmericain = 6,
    HockeySurGlace = 7,
    Baseball = 8,
    MMA = 9,
    Equitation = 11,
    HobbyHorse = 12,
    CoursesCanines = 13,
    CoursesDeLapins = 14,
    Fauconnerie = 15,
    Autre = 99,
}
