export enum Tag {
    // ——— Capacités physiques ———
    Vitesse = 1,
    Endurance = 2,
    Puissance = 3,
    Reflexes = 4,
    Agilite = 5,
    Explosivite = 6,
    Souplesse = 7,
    Coordination = 8,
    Equilibre = 9,

    // ——— Capacités techniques ———
    Technique = 10,
    MaitriseDuBallon = 11,
    Precision = 12,
    Finition = 13,
    PasseDecisive = 14,
    TirCadre = 15,
    Dribble = 16,
    JeuDeTete = 17,
    Tacle = 18,
    Interception = 19,
    GesteTechnique = 20,
    Polyvalence = 21,

    // ——— Intelligence et mental ———
    IntelligenceTactique = 22,
    LectureDuJeu = 23,
    Anticipation = 24,
    Concentration = 25,
    Mental = 26,
    SangFroid = 27,
    Maturite = 28,
    GestionDuTemps = 29,
    Resilience = 30,
    VisionDeJeu = 31,
    Decisif = 32,
    PriseDeDecision = 33,
    Adaptabilite = 34,
    Competiteur = 35,
    Leadership = 36,
    EspritDEquipe = 37,
    Determination = 38,
    ConfianceEnSoi = 39,
    Motivation = 40,
    ApprentissageRapide = 41,
    Discipline = 42,
    Regularite = 43,
    EnduranceMentale = 44,

    // ——— Comportement et personnalité ———
    Travailleur = 45,
    Perseverant = 46,
    Passionne = 47,
    Humilite = 48,
    Exemplaire = 49,
    Respectueux = 50,
    Charismatique = 51,
    Dynamique = 52,
    Engage = 53,
    FairPlay = 54,
    InfluenceurDeVestiaire = 55,
    AttitudeProfessionnelle = 56,

    // ——— Créativité et style ———
    Creativite = 57,
    StyleDeJeuUnique = 58,
    Spectaculaire = 59,
    Showman = 60,
    Imagination = 61,

    // ——— Potentiel / projection ———
    GrosPotentiel = 62,
    EnProgres = 63,
    JeunePrometteur = 64,
    TalentNaturel = 65,
}
